openapi: 3.0.1
info:
  title: GPT Calendar – Young Minds
  description: Plugin que permite crear y cancelar eventos en el calendario de Young Minds mediante lenguaje natural.
  version: "1.0.0"
servers:
  - url: https://gpt-calendar-young-minds.onrender.com
paths:
  /crear-evento:
    post:
      summary: Crear un nuevo evento en Google Calendar
      operationId: crearEvento
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Título del evento
                start_time:
                  type: string
                  format: date-time
                  description: Fecha y hora de inicio (ISO 8601)
                end_time:
                  type: string
                  format: date-time
                  description: Fecha y hora de fin (ISO 8601)
                location:
                  type: string
                  description: Ubicación del evento (opcional)
              required:
                - title
                - start_time
                - end_time
      responses:
        '200':
          description: Evento creado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  event_id:
                    type: string
  /cancel-evento:
    post:
      summary: Cancelar un evento existente en Google Calendar
      operationId: cancelarEvento
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                event_id:
                  type: string
                  description: ID del evento a cancelar
              required:
                - event_id
      responses:
        '200':
          description: Evento cancelado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
